//
// AnswerOptionDto.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct AnswerOptionDto: Codable {

    public var question: Int?
    public var option: Int?
    public var answer: String?

    public init(question: Int?, option: Int?, answer: String?) {
        self.question = question
        self.option = option
        self.answer = answer
    }


}

