//
// Body.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Body: Codable {

    public var principal: Jwt?
    public var answers: [String:String]?

    public init(principal: Jwt?, answers: [String:String]?) {
        self.principal = principal
        self.answers = answers
    }


}

