//
// Jwt.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Jwt: Codable {

    public var tokenValue: String?
    public var issuedAt: Date?
    public var expiresAt: Date?
    public var headers: [String:JSONValue]?
    public var claims: [String:JSONValue]?
    public var _id: String?
    public var subject: String?
    public var audience: [String]?
    public var notBefore: Date?
    public var issuer: String?

    public init(tokenValue: String?, issuedAt: Date?, expiresAt: Date?, headers: [String:JSONValue]?, claims: [String:JSONValue]?, _id: String?, subject: String?, audience: [String]?, notBefore: Date?, issuer: String?) {
        self.tokenValue = tokenValue
        self.issuedAt = issuedAt
        self.expiresAt = expiresAt
        self.headers = headers
        self.claims = claims
        self._id = _id
        self.subject = subject
        self.audience = audience
        self.notBefore = notBefore
        self.issuer = issuer
    }

    public enum CodingKeys: String, CodingKey { 
        case tokenValue
        case issuedAt
        case expiresAt
        case headers
        case claims
        case _id = "id"
        case subject
        case audience
        case notBefore
        case issuer
    }

}

