//
// ApplicationVersionDto.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Application version */

public struct ApplicationVersionDto: Codable {

    public var android: VersionDto?
    public var ios: VersionDto?

    public init(android: VersionDto?, ios: VersionDto?) {
        self.android = android
        self.ios = ios
    }


}

