//
// AttenuationFactorDto.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Attenuation factor */

public struct AttenuationFactorDto: Codable {

    public var low: Double?
    public var medium: Double?

    public init(low: Double?, medium: Double?) {
        self.low = low
        self.medium = medium
    }


}

