//
// AttenuationDurationThresholdsDto.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Attenuation duration thresholds */

public struct AttenuationDurationThresholdsDto: Codable {

    public var low: Int?
    public var medium: Int?

    public init(low: Int?, medium: Int?) {
        self.low = low
        self.medium = medium
    }


}

