//
// CcaaKeyValueDto.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct CcaaKeyValueDto: Codable {

    public var _id: String?
    public var _description: String?
    public var phone: String?
    public var email: String?
    public var additionalInfo: String?

    public init(_id: String?, _description: String?, phone: String?, email: String?, additionalInfo: String?) {
        self._id = _id
        self._description = _description
        self.phone = phone
        self.email = email
        self.additionalInfo = additionalInfo
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case _description = "description"
        case phone
        case email
        case additionalInfo
    }

}

