//
// ExposureConfigurationDto.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Exposure configuration */

public struct ExposureConfigurationDto: Codable {

    public var transmission: RiskLevelDataDto?
    public var duration: RiskLevelDataDto?
    public var days: RiskLevelDataDto?
    public var attenuation: RiskLevelDataDto?

    public init(transmission: RiskLevelDataDto?, duration: RiskLevelDataDto?, days: RiskLevelDataDto?, attenuation: RiskLevelDataDto?) {
        self.transmission = transmission
        self.duration = duration
        self.days = days
        self.attenuation = attenuation
    }


}

