//
// RiskScoreClassificationDto.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Risk score classification */

public struct RiskScoreClassificationDto: Codable {

    public var label: String?
    public var minValue: Int?
    public var maxValue: Int?

    public init(label: String?, minValue: Int?, maxValue: Int?) {
        self.label = label
        self.minValue = minValue
        self.maxValue = maxValue
    }


}

