//
// SettingsDto.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Application settings */

public struct SettingsDto: Codable {

    public var exposureConfiguration: ExposureConfigurationDto?
    /** Minimum risk score */
    public var minRiskScore: Int64?
    /** Risk score classification */
    public var riskScoreClassification: [RiskScoreClassificationDto]?
    public var attenuationDurationThresholds: AttenuationDurationThresholdsDto?

    public init(exposureConfiguration: ExposureConfigurationDto?, minRiskScore: Int64?, riskScoreClassification: [RiskScoreClassificationDto]?, attenuationDurationThresholds: AttenuationDurationThresholdsDto?) {
        self.exposureConfiguration = exposureConfiguration
        self.minRiskScore = minRiskScore
        self.riskScoreClassification = riskScoreClassification
        self.attenuationDurationThresholds = attenuationDurationThresholds
    }


}

