//
// UuidDto.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct UuidDto: Codable {

    public var uuid: String?

    public init(uuid: String?) {
        self.uuid = uuid
    }

}

