//
// VersionDto.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** iOS version information */

public struct VersionDto: Codable {

    /** Version identifier */
    public var version: String?
    /** Compilation identifier */
    public var compilation: Int?

    public init(version: String?, compilation: Int?) {
        self.version = version
        self.compilation = compilation
    }


}

