//
// Code.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** The Code to be verified */

public struct Code: Codable {

    /** Date the patient indicates that he/she is infected */
    public var date: Date
    /** 12 digits code */
    public var code: String

    public init(date: Date, code: String) {
        self.date = date
        self.code = code
    }


}

