//
// Tan.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** The transaction number model. */

public struct Tan: Codable {

    public var tan: String

    public init(tan: String) {
        self.tan = tan
    }


}

