//
// KpiDto.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct KpiDto: Codable {

    public enum Kpi: String, Codable { 
        case daysSinceLastExposure = "DAYS_SINCE_LAST_EXPOSURE"
        case matchedKeyCount = "MATCHED_KEY_COUNT"
        case maximumRiskScore = "MAXIMUM_RISK_SCORE"
        case attenuationDurations1 = "ATTENUATION_DURATIONS_1"
        case attenuationDurations2 = "ATTENUATION_DURATIONS_2"
        case attenuationDurations3 = "ATTENUATION_DURATIONS_3"
        case summationRiskScore = "SUMMATION_RISK_SCORE"
    }
    public var kpi: Kpi?
    public var timestamp: String?
    public var value: Int?

    public init(kpi: Kpi?, timestamp: String?, value: Int?) {
        self.kpi = kpi
        self.timestamp = timestamp
        self.value = value
    }


}

